site_name: Test-Driven Development with Flask
docs_dir: 'text'
site_dir: 'docs'
nav: 
  - Home: index.md
  - One:
    - Intro to TDD: ch1.md
    - Types of Tests: ch2.md
  - Two: 
    - Intro to Objects: ch3.md
    - TDD with Objects: ch4.md
  - Three: 
    - The Internet: ch5.md
    - TDD Online: ch6.md
  - Four:
    - Intro to Flask: ch7.md
    - Smallest App: ch8.md
  