site_name: Test-Driven Development with Flask
docs_dir: 'text'
site_dir: 'docs'
nav: 
  - Home: index.md
  - One: ch1.md
  - Two: ch2.md
  - Three: ch3.md
  - Four: ch4.md
  - Five: ch5.md
  - Six: ch6.md
  - Seven: ch7.md