site_name: Test-Driven Development with Flask
docs_dir: 'text'
site_dir: 'docs'
nav: 
  - Home: index.md
  - One:
    - 1. Intro to TDD: ch1.md
    - 2. Types of Tests: ch2.md
  - Two: 
    - 3. Intro to Objects: ch3.md
    - 4. TDD with Objects: ch4.md
  - Three: 
    - 5. The Internet: ch5.md
    - 6. TDD Online: ch6.md
  - Four:
    - 7. Intro to Flask: ch7.md
    - 8. Smallest App: ch8.md
  - Five:
    - 9. Intro to HTML: ch9.md
    - 10. Intro to Templates: ch10.md
  - Six:
    - 11. Decorators: ch11.md
    - 12. Templates the TDD Way: ch12.md
  - Seven:
    - 13. Forms the TDD way: ch13.md 
    - 14. Databases and Login: ch14.md